/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ComponenteGrafico;
import javax.swing.ImageIcon;

/**
 *
 * @author i62rapad
 */
public class ComponenteGrafico extends javax.swing.JPanel {
    private String textBoton1;
    private String textBoton2;
    private int estado;

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public String getTextBoton1() {
        return textBoton1;
    }

    public void setTextBoton1(String textBoton1) {
        jButton1.setText(textBoton1);
        this.textBoton1 = textBoton1;
    }

    public String getTextBoton2() {
        return textBoton2;
    }

    public void setTextBoton2(String textBoton2) {
        jButton2.setText(textBoton2);
        this.textBoton2 = textBoton2;
    }
    
    private void setImage(){
        switch(this.getEstado()){
            case 0:
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/ico/rueda.jpg")));
                break;
            case 1:
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/ico/rueda45.jpg")));
                break;
            case 2:
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/ico/rueda90.jpg")));
                break;
            case 3:
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/ico/rueda135.jpg")));
                break;
            case 4:
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/ico/rueda180.jpg")));
                break;
            case 5:
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/ico/rueda225.jpg")));
                break;
            case 6:
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/ico/rueda270.jpg")));
                break;
            case 7:
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/ico/rueda315.jpg")));
                break;
        }
    }
    
    public void setRuedaIzquierda(){
        if(getEstado() == 0){
            this.setEstado(7);
        }
        else{
            this.setEstado((this.getEstado() - 1)%8);
        }
        
        setImage();
    }
    
    public void setRuedaDerecha(){
        this.setEstado((this.getEstado() + 1)%8);
        setImage();
    }
    
    /**
     * Creates new form ComponenteGrafico
     */
    public ComponenteGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.setFocusable(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/rueda.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jLabel1))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        setRuedaIzquierda();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        setRuedaDerecha();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(evt.getX() >= 138 && evt.getX() <= 158 && evt.getY() >= 66 && evt.getY() <= 86){
            setEstado(0);
            setImage();
        }
        
        if(evt.getX() >= 180 && evt.getX() <= 200 && evt.getY() >= 85 && evt.getY() <= 105){
            setEstado(1);
            setImage();
        }
        
        if(evt.getX() >= 196 && evt.getX() <= 216 && evt.getY() >= 121 && evt.getY() <= 141){
            setEstado(2);
            setImage();
        }
        
        if(evt.getX() >= 181 && evt.getX() <= 201 && evt.getY() >= 166 && evt.getY() <= 186){
            setEstado(3);
            setImage();
        }

        if(evt.getX() >= 137 && evt.getX() <= 157 && evt.getY() >= 183 && evt.getY() <= 203){
            setEstado(4);
            setImage();
        }
        
        if(evt.getX() >= 95 && evt.getX() <= 115 && evt.getY() >= 165 && evt.getY() <= 185){
            setEstado(5);
            setImage();
        }
        
        if(evt.getX() >= 79 && evt.getX() <= 99 && evt.getY() >= 121 && evt.getY() <= 141){
            setEstado(6);
            setImage();
        }
        
        if(evt.getX() >= 97 && evt.getX() <= 117 && evt.getY() >= 83 && evt.getY() <= 103){
            setEstado(7);
            setImage();
        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
